namespace SiliconSteelAdhesionTester.Forms
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Panel pnlNavigation;
        private System.Windows.Forms.Panel pnlOverview;
        private System.Windows.Forms.Panel pnlFlow;
        private System.Windows.Forms.Panel pnlStationHeader;
        private System.Windows.Forms.Panel pnlProcess;
        private System.Windows.Forms.Panel pnlBottom;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblConnection;
        private System.Windows.Forms.Label lblUser;
        private System.Windows.Forms.Label lblPermission;
        private System.Windows.Forms.Label lblHome;
        private System.Windows.Forms.Label lblMode;
        private System.Windows.Forms.Label lblBarcode;
        private System.Windows.Forms.Label lblTotalCount;
        private System.Windows.Forms.Label lblShiftCount;
        private System.Windows.Forms.Label lblCurrentTask;
        private System.Windows.Forms.Label lblMaterialType;
        private System.Windows.Forms.Label lblFlow1;
        private System.Windows.Forms.Label lblFlow2;
        private System.Windows.Forms.Label lblFlow3;
        private System.Windows.Forms.Label lblFlow4;
        private System.Windows.Forms.Label lblFlow5;
        private System.Windows.Forms.Label lblFlow6;
        private System.Windows.Forms.Label lblFlow7;
        private System.Windows.Forms.Label lblFlow8;
        private System.Windows.Forms.Label lblFlowMessage;
        private System.Windows.Forms.Label lblFlowLegend;
        private System.Windows.Forms.Label lblStationStatus1;
        private System.Windows.Forms.Label lblStationStatus2;
        private System.Windows.Forms.Label lblStationStatus3;
        private System.Windows.Forms.Label lblStationStatus4;
        private System.Windows.Forms.Label lblStep1;
        private System.Windows.Forms.Label lblStep2;
        private System.Windows.Forms.Label lblStep3;
        private System.Windows.Forms.Label lblStep4;
        private System.Windows.Forms.Label lblQueueTitle;
        private System.Windows.Forms.Label lblLogTitle;
        private System.Windows.Forms.Panel pnlRun1;
        private System.Windows.Forms.Panel pnlRun2;
        private System.Windows.Forms.Panel pnlRun3;
        private System.Windows.Forms.Panel pnlRun4;
        private System.Windows.Forms.Panel pnlReady1;
        private System.Windows.Forms.Panel pnlReady2;
        private System.Windows.Forms.Panel pnlReady3;
        private System.Windows.Forms.Panel pnlReady4;
        private System.Windows.Forms.Panel pnlDone1;
        private System.Windows.Forms.Panel pnlDone2;
        private System.Windows.Forms.Panel pnlDone3;
        private System.Windows.Forms.Panel pnlDone4;
        private System.Windows.Forms.Button btnAutoMode;
        private System.Windows.Forms.Button btnManualMode;
        private System.Windows.Forms.Button btnLineStart;
        private System.Windows.Forms.Button btnLinePause;
        private System.Windows.Forms.Button btnLineStop;
        private System.Windows.Forms.Button btnLineHome;
        private System.Windows.Forms.Button btnFaultReset;
        private System.Windows.Forms.Button btnVision;
        private System.Windows.Forms.Button btnDebug;
        private System.Windows.Forms.Button btnRecords;
        private System.Windows.Forms.Button btnFaultLogs;
        private System.Windows.Forms.Button btnS1Start;
        private System.Windows.Forms.Button btnS2Start;
        private System.Windows.Forms.Button btnS3Start;
        private System.Windows.Forms.Button btnS4Start;
        private System.Windows.Forms.Button btnS1Continuous;
        private System.Windows.Forms.Button btnS2Continuous;
        private System.Windows.Forms.Button btnS3Continuous;
        private System.Windows.Forms.Button btnS4Continuous;
        private System.Windows.Forms.Button btnNavMonitor;
        private System.Windows.Forms.Button btnNavVision;
        private System.Windows.Forms.Button btnNavRecords;
        private System.Windows.Forms.Button btnNavLogs;
        private System.Windows.Forms.Button btnNavSettings;
        private System.Windows.Forms.DataGridView dgvTasks;
        private System.Windows.Forms.DataGridViewTextBoxColumn colTaskId;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMaterial;
        private System.Windows.Forms.DataGridViewTextBoxColumn colTaskState;
        private System.Windows.Forms.TextBox txtRuntimeLog;

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.pnlNavigation = new System.Windows.Forms.Panel();
            this.pnlOverview = new System.Windows.Forms.Panel();
            this.pnlFlow = new System.Windows.Forms.Panel();
            this.pnlStationHeader = new System.Windows.Forms.Panel();
            this.pnlProcess = new System.Windows.Forms.Panel();
            this.pnlBottom = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblConnection = new System.Windows.Forms.Label();
            this.lblUser = new System.Windows.Forms.Label();
            this.lblPermission = new System.Windows.Forms.Label();
            this.lblHome = new System.Windows.Forms.Label();
            this.lblMode = new System.Windows.Forms.Label();
            this.lblBarcode = new System.Windows.Forms.Label();
            this.lblTotalCount = new System.Windows.Forms.Label();
            this.lblShiftCount = new System.Windows.Forms.Label();
            this.lblCurrentTask = new System.Windows.Forms.Label();
            this.lblMaterialType = new System.Windows.Forms.Label();
            this.lblFlow1 = new System.Windows.Forms.Label();
            this.lblFlow2 = new System.Windows.Forms.Label();
            this.lblFlow3 = new System.Windows.Forms.Label();
            this.lblFlow4 = new System.Windows.Forms.Label();
            this.lblFlow5 = new System.Windows.Forms.Label();
            this.lblFlow6 = new System.Windows.Forms.Label();
            this.lblFlow7 = new System.Windows.Forms.Label();
            this.lblFlow8 = new System.Windows.Forms.Label();
            this.lblFlowMessage = new System.Windows.Forms.Label();
            this.lblFlowLegend = new System.Windows.Forms.Label();
            this.lblStationStatus1 = new System.Windows.Forms.Label();
            this.lblStationStatus2 = new System.Windows.Forms.Label();
            this.lblStationStatus3 = new System.Windows.Forms.Label();
            this.lblStationStatus4 = new System.Windows.Forms.Label();
            this.lblStep1 = new System.Windows.Forms.Label();
            this.lblStep2 = new System.Windows.Forms.Label();
            this.lblStep3 = new System.Windows.Forms.Label();
            this.lblStep4 = new System.Windows.Forms.Label();
            this.lblQueueTitle = new System.Windows.Forms.Label();
            this.lblLogTitle = new System.Windows.Forms.Label();
            this.pnlRun1 = new System.Windows.Forms.Panel();
            this.pnlRun2 = new System.Windows.Forms.Panel();
            this.pnlRun3 = new System.Windows.Forms.Panel();
            this.pnlRun4 = new System.Windows.Forms.Panel();
            this.pnlReady1 = new System.Windows.Forms.Panel();
            this.pnlReady2 = new System.Windows.Forms.Panel();
            this.pnlReady3 = new System.Windows.Forms.Panel();
            this.pnlReady4 = new System.Windows.Forms.Panel();
            this.pnlDone1 = new System.Windows.Forms.Panel();
            this.pnlDone2 = new System.Windows.Forms.Panel();
            this.pnlDone3 = new System.Windows.Forms.Panel();
            this.pnlDone4 = new System.Windows.Forms.Panel();
            this.btnAutoMode = new System.Windows.Forms.Button();
            this.btnManualMode = new System.Windows.Forms.Button();
            this.btnLineStart = new System.Windows.Forms.Button();
            this.btnLinePause = new System.Windows.Forms.Button();
            this.btnLineStop = new System.Windows.Forms.Button();
            this.btnLineHome = new System.Windows.Forms.Button();
            this.btnFaultReset = new System.Windows.Forms.Button();
            this.btnVision = new System.Windows.Forms.Button();
            this.btnDebug = new System.Windows.Forms.Button();
            this.btnRecords = new System.Windows.Forms.Button();
            this.btnFaultLogs = new System.Windows.Forms.Button();
            this.btnS1Start = new System.Windows.Forms.Button();
            this.btnS2Start = new System.Windows.Forms.Button();
            this.btnS3Start = new System.Windows.Forms.Button();
            this.btnS4Start = new System.Windows.Forms.Button();
            this.btnS1Continuous = new System.Windows.Forms.Button();
            this.btnS2Continuous = new System.Windows.Forms.Button();
            this.btnS3Continuous = new System.Windows.Forms.Button();
            this.btnS4Continuous = new System.Windows.Forms.Button();
            this.btnNavMonitor = new System.Windows.Forms.Button();
            this.btnNavVision = new System.Windows.Forms.Button();
            this.btnNavRecords = new System.Windows.Forms.Button();
            this.btnNavLogs = new System.Windows.Forms.Button();
            this.btnNavSettings = new System.Windows.Forms.Button();
            this.dgvTasks = new System.Windows.Forms.DataGridView();
            this.colTaskId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMaterial = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colTaskState = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.txtRuntimeLog = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTasks)).BeginInit();
            this.SuspendLayout();

            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(18, 32, 49);
            this.pnlHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Height = 72;
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Microsoft YaHei UI", 20F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(24, 17);
            this.lblTitle.Text = "硅钢附着力测试仪";
            this.lblConnection.AutoSize = true;
            this.lblConnection.Font = new System.Drawing.Font("Microsoft YaHei UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblConnection.ForeColor = System.Drawing.Color.Gold;
            this.lblConnection.Location = new System.Drawing.Point(370, 25);
            this.lblConnection.Text = "● PLC连接中";
            this.lblUser.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.lblUser.AutoSize = true;
            this.lblUser.ForeColor = System.Drawing.Color.Gainsboro;
            this.lblUser.Location = new System.Drawing.Point(1020, 16);
            this.lblUser.Text = "用户：-";
            this.lblPermission.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.lblPermission.AutoSize = true;
            this.lblPermission.ForeColor = System.Drawing.Color.Silver;
            this.lblPermission.Location = new System.Drawing.Point(1020, 43);
            this.lblPermission.Text = "权限：-";
            this.lblHome.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.lblHome.BackColor = System.Drawing.Color.FromArgb(35, 156, 96);
            this.lblHome.ForeColor = System.Drawing.Color.White;
            this.lblHome.Location = new System.Drawing.Point(1220, 14);
            this.lblHome.Size = new System.Drawing.Size(92, 44);
            this.lblHome.Text = "在原位";
            this.lblHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblMode.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.lblMode.BackColor = System.Drawing.Color.FromArgb(35, 156, 96);
            this.lblMode.ForeColor = System.Drawing.Color.White;
            this.lblMode.Location = new System.Drawing.Point(1320, 14);
            this.lblMode.Size = new System.Drawing.Size(96, 44);
            this.lblMode.Text = "自动模式";
            this.lblMode.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.pnlHeader.Controls.Add(this.lblTitle);
            this.pnlHeader.Controls.Add(this.lblConnection);
            this.pnlHeader.Controls.Add(this.lblUser);
            this.pnlHeader.Controls.Add(this.lblPermission);
            this.pnlHeader.Controls.Add(this.lblHome);
            this.pnlHeader.Controls.Add(this.lblMode);

            this.pnlNavigation.BackColor = System.Drawing.Color.FromArgb(25, 43, 63);
            this.pnlNavigation.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlNavigation.Width = 176;
            this.btnNavMonitor.BackColor = System.Drawing.Color.FromArgb(38, 112, 190);
            this.btnNavMonitor.FlatAppearance.BorderSize = 0;
            this.btnNavMonitor.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNavMonitor.ForeColor = System.Drawing.Color.White;
            this.btnNavMonitor.Location = new System.Drawing.Point(0, 24);
            this.btnNavMonitor.Size = new System.Drawing.Size(176, 52);
            this.btnNavMonitor.Text = "生产监控";
            this.btnNavVision.FlatAppearance.BorderSize = 0;
            this.btnNavVision.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNavVision.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnNavVision.Location = new System.Drawing.Point(0, 78);
            this.btnNavVision.Size = new System.Drawing.Size(176, 52);
            this.btnNavVision.Text = "视觉检测";
            this.btnNavRecords.FlatAppearance.BorderSize = 0;
            this.btnNavRecords.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNavRecords.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnNavRecords.Location = new System.Drawing.Point(0, 186);
            this.btnNavRecords.Size = new System.Drawing.Size(176, 52);
            this.btnNavRecords.Text = "检测记录";
            this.btnNavLogs.FlatAppearance.BorderSize = 0;
            this.btnNavLogs.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNavLogs.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnNavLogs.Location = new System.Drawing.Point(0, 240);
            this.btnNavLogs.Size = new System.Drawing.Size(176, 52);
            this.btnNavLogs.Text = "运行日志";
            this.btnNavSettings.FlatAppearance.BorderSize = 0;
            this.btnNavSettings.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNavSettings.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnNavSettings.Location = new System.Drawing.Point(0, 294);
            this.btnNavSettings.Size = new System.Drawing.Size(176, 52);
            this.btnNavSettings.Text = "系统设置";
            this.btnVision.Location = new System.Drawing.Point(14, 330);
            this.btnVision.Size = new System.Drawing.Size(148, 38);
            this.btnVision.Text = "打开视觉检测";
            this.btnVision.Visible = false;
            this.btnDebug.FlatAppearance.BorderSize = 0;
            this.btnDebug.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDebug.ForeColor = System.Drawing.Color.Gainsboro;
            this.btnDebug.Location = new System.Drawing.Point(0, 132);
            this.btnDebug.Size = new System.Drawing.Size(176, 52);
            this.btnDebug.Text = "工程师调试";
            this.btnRecords.Location = new System.Drawing.Point(14, 422);
            this.btnRecords.Size = new System.Drawing.Size(148, 38);
            this.btnRecords.Text = "查看检测记录";
            this.btnRecords.Visible = false;
            this.btnFaultLogs.Location = new System.Drawing.Point(14, 468);
            this.btnFaultLogs.Size = new System.Drawing.Size(148, 38);
            this.btnFaultLogs.Text = "查看运行日志";
            this.btnFaultLogs.Visible = false;
            this.pnlNavigation.Controls.Add(this.btnNavMonitor);
            this.pnlNavigation.Controls.Add(this.btnNavVision);
            this.pnlNavigation.Controls.Add(this.btnNavRecords);
            this.pnlNavigation.Controls.Add(this.btnNavLogs);
            this.pnlNavigation.Controls.Add(this.btnNavSettings);
            this.pnlNavigation.Controls.Add(this.btnDebug);

            this.pnlOverview.BackColor = System.Drawing.Color.White;
            this.pnlOverview.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlOverview.Height = 104;
            this.lblCurrentTask.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.lblCurrentTask.ForeColor = System.Drawing.Color.DimGray;
            this.lblCurrentTask.Location = new System.Drawing.Point(22, 13);
            this.lblCurrentTask.Size = new System.Drawing.Size(220, 22);
            this.lblCurrentTask.Text = "当前检验号 · 等待扫码/总控任务";
            this.lblBarcode.Font = new System.Drawing.Font("Microsoft YaHei UI", 15F, System.Drawing.FontStyle.Bold);
            this.lblBarcode.ForeColor = System.Drawing.Color.FromArgb(30, 83, 140);
            this.lblBarcode.Location = new System.Drawing.Point(20, 40);
            this.lblBarcode.Size = new System.Drawing.Size(270, 40);
            this.lblBarcode.Text = "-";
            this.lblMaterialType.ForeColor = System.Drawing.Color.DimGray;
            this.lblMaterialType.Location = new System.Drawing.Point(330, 13);
            this.lblMaterialType.Size = new System.Drawing.Size(200, 22);
            this.lblMaterialType.Text = "等待任务数据";
            this.lblTotalCount.Font = new System.Drawing.Font("Microsoft YaHei UI", 15F, System.Drawing.FontStyle.Bold);
            this.lblTotalCount.Location = new System.Drawing.Point(906, 39);
            this.lblTotalCount.Size = new System.Drawing.Size(150, 40);
            this.lblTotalCount.Text = "0 PCS";
            this.lblShiftCount.Font = new System.Drawing.Font("Microsoft YaHei UI", 15F, System.Drawing.FontStyle.Bold);
            this.lblShiftCount.Location = new System.Drawing.Point(1090, 39);
            this.lblShiftCount.Size = new System.Drawing.Size(150, 40);
            this.lblShiftCount.Text = "0 PCS";
            this.pnlOverview.Controls.Add(this.lblCurrentTask);
            this.pnlOverview.Controls.Add(this.lblBarcode);
            this.pnlOverview.Controls.Add(this.lblMaterialType);
            this.pnlOverview.Controls.Add(this.lblTotalCount);
            this.pnlOverview.Controls.Add(this.lblShiftCount);

            this.pnlFlow.BackColor = System.Drawing.Color.FromArgb(243, 246, 250);
            this.pnlFlow.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlFlow.Height = 100;
            this.lblFlow1.Location = new System.Drawing.Point(14, 18);
            this.lblFlow2.Location = new System.Drawing.Point(169, 18);
            this.lblFlow3.Location = new System.Drawing.Point(324, 18);
            this.lblFlow4.Location = new System.Drawing.Point(479, 18);
            this.lblFlow5.Location = new System.Drawing.Point(634, 18);
            this.lblFlow6.Location = new System.Drawing.Point(789, 18);
            this.lblFlow7.Location = new System.Drawing.Point(944, 18);
            this.lblFlow8.Location = new System.Drawing.Point(1099, 18);
            this.lblFlow1.Size = new System.Drawing.Size(149, 42);
            this.lblFlow2.Size = new System.Drawing.Size(149, 42);
            this.lblFlow3.Size = new System.Drawing.Size(149, 42);
            this.lblFlow4.Size = new System.Drawing.Size(149, 42);
            this.lblFlow5.Size = new System.Drawing.Size(149, 42);
            this.lblFlow6.Size = new System.Drawing.Size(149, 42);
            this.lblFlow7.Size = new System.Drawing.Size(149, 42);
            this.lblFlow8.Size = new System.Drawing.Size(149, 42);
            this.lblFlow1.Text = "1 扫码取样";
            this.lblFlow2.Text = "2 压弯前拍照";
            this.lblFlow3.Text = "3 固定位置压弯";
            this.lblFlow4.Text = "4 压弯后拍照";
            this.lblFlow5.Text = "5 胶带粘取";
            this.lblFlow6.Text = "6 OpenCV分析";
            this.lblFlow7.Text = "7 脱落率判定";
            this.lblFlow8.Text = "8 保存上传";
            this.lblFlow1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblFlow1.BackColor = System.Drawing.Color.Gold;
            this.lblFlow1.ForeColor = System.Drawing.Color.FromArgb(45, 40, 15);
            this.lblFlow2.BackColor = System.Drawing.Color.White;
            this.lblFlow3.BackColor = System.Drawing.Color.White;
            this.lblFlow4.BackColor = System.Drawing.Color.White;
            this.lblFlow5.BackColor = System.Drawing.Color.White;
            this.lblFlow6.BackColor = System.Drawing.Color.White;
            this.lblFlow7.BackColor = System.Drawing.Color.White;
            this.lblFlow8.BackColor = System.Drawing.Color.White;
            this.lblFlowMessage.AutoSize = false;
            this.lblFlowMessage.ForeColor = System.Drawing.Color.FromArgb(38, 112, 190);
            this.lblFlowMessage.Location = new System.Drawing.Point(14, 66);
            this.lblFlowMessage.Size = new System.Drawing.Size(632, 24);
            this.lblFlowMessage.Text = "等待总控下达任务";
            this.lblFlowLegend.AutoSize = false;
            this.lblFlowLegend.ForeColor = System.Drawing.Color.Gray;
            this.lblFlowLegend.Location = new System.Drawing.Point(820, 66);
            this.lblFlowLegend.Size = new System.Drawing.Size(430, 24);
            this.lblFlowLegend.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblFlowLegend.Text = "绿色：完成  蓝色：执行中  黄色：暂停  红色：异常";
            this.pnlFlow.Controls.Add(this.lblFlow1);
            this.pnlFlow.Controls.Add(this.lblFlow2);
            this.pnlFlow.Controls.Add(this.lblFlow3);
            this.pnlFlow.Controls.Add(this.lblFlow4);
            this.pnlFlow.Controls.Add(this.lblFlow5);
            this.pnlFlow.Controls.Add(this.lblFlow6);
            this.pnlFlow.Controls.Add(this.lblFlow7);
            this.pnlFlow.Controls.Add(this.lblFlow8);
            this.pnlFlow.Controls.Add(this.lblFlowMessage);
            this.pnlFlow.Controls.Add(this.lblFlowLegend);

            this.pnlStationHeader.BackColor = System.Drawing.Color.White;
            this.pnlStationHeader.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                | System.Windows.Forms.AnchorStyles.Left)
                | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlStationHeader.Location = new System.Drawing.Point(176, 276);
            this.pnlStationHeader.Size = new System.Drawing.Size(1264, 548);
            this.lblQueueTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblQueueTitle.Font = new System.Drawing.Font("Microsoft YaHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblQueueTitle.Height = 42;
            this.lblQueueTitle.Padding = new System.Windows.Forms.Padding(12, 10, 0, 0);
            this.lblQueueTitle.Text = "待检任务";
            this.dgvTasks.AllowUserToAddRows = false;
            this.dgvTasks.AllowUserToDeleteRows = false;
            this.dgvTasks.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTasks.BackgroundColor = System.Drawing.Color.White;
            this.dgvTasks.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvTasks.ColumnHeadersHeight = 34;
            this.dgvTasks.Dock = System.Windows.Forms.DockStyle.Top;
            this.dgvTasks.Height = 232;
            this.dgvTasks.ReadOnly = true;
            this.dgvTasks.RowHeadersVisible = false;
            this.dgvTasks.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.colTaskId.HeaderText = "检验号";
            this.colTaskId.Name = "TaskId";
            this.colMaterial.HeaderText = "类型";
            this.colMaterial.Name = "Material";
            this.colTaskState.HeaderText = "状态";
            this.colTaskState.Name = "State";
            this.dgvTasks.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colTaskId, this.colMaterial, this.colTaskState });
            this.dgvTasks.Rows.Add("-", "-", "等待LIMS任务");
            this.lblLogTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblLogTitle.Font = new System.Drawing.Font("Microsoft YaHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblLogTitle.Height = 42;
            this.lblLogTitle.Padding = new System.Windows.Forms.Padding(12, 10, 0, 0);
            this.lblLogTitle.Text = "最新运行日志";
            this.txtRuntimeLog.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.txtRuntimeLog.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtRuntimeLog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtRuntimeLog.Multiline = true;
            this.txtRuntimeLog.ReadOnly = true;
            this.txtRuntimeLog.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtRuntimeLog.Text = "系统启动，等待PLC和任务数据……";
            this.pnlStationHeader.Controls.Add(this.txtRuntimeLog);
            this.pnlStationHeader.Controls.Add(this.lblLogTitle);
            this.pnlStationHeader.Controls.Add(this.dgvTasks);
            this.pnlStationHeader.Controls.Add(this.lblQueueTitle);

            this.pnlProcess.BackColor = System.Drawing.Color.White;
            this.pnlProcess.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlProcess.Visible = false;
            this.lblStep1.Location = new System.Drawing.Point(22, 42);
            this.lblStep2.Location = new System.Drawing.Point(22, 112);
            this.lblStep3.Location = new System.Drawing.Point(22, 182);
            this.lblStep4.Location = new System.Drawing.Point(22, 252);
            this.lblStep1.Size = new System.Drawing.Size(92, 42);
            this.lblStep2.Size = new System.Drawing.Size(92, 42);
            this.lblStep3.Size = new System.Drawing.Size(92, 42);
            this.lblStep4.Size = new System.Drawing.Size(92, 42);
            this.lblStep1.Text = "S1  0步";
            this.lblStep2.Text = "S2  0步";
            this.lblStep3.Text = "S3  0步";
            this.lblStep4.Text = "S4  0步";
            this.lblStep1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblStep2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblStep3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblStep4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblStationStatus1.Location = new System.Drawing.Point(128, 42);
            this.lblStationStatus2.Location = new System.Drawing.Point(128, 112);
            this.lblStationStatus3.Location = new System.Drawing.Point(128, 182);
            this.lblStationStatus4.Location = new System.Drawing.Point(128, 252);
            this.lblStationStatus1.Size = new System.Drawing.Size(430, 42);
            this.lblStationStatus2.Size = new System.Drawing.Size(430, 42);
            this.lblStationStatus3.Size = new System.Drawing.Size(430, 42);
            this.lblStationStatus4.Size = new System.Drawing.Size(430, 42);
            this.lblStationStatus1.BackColor = System.Drawing.Color.FromArgb(246, 248, 251);
            this.lblStationStatus2.BackColor = System.Drawing.Color.FromArgb(246, 248, 251);
            this.lblStationStatus3.BackColor = System.Drawing.Color.FromArgb(246, 248, 251);
            this.lblStationStatus4.BackColor = System.Drawing.Color.FromArgb(246, 248, 251);
            this.lblStationStatus1.Text = "取放料工位 · 等待PLC数据";
            this.lblStationStatus2.Text = "取向附着性测试 · 等待PLC数据";
            this.lblStationStatus3.Text = "非取向压弯 · 等待PLC数据";
            this.lblStationStatus4.Text = "非取向胶带检测 · 等待PLC数据";
            this.lblStationStatus1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStationStatus2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStationStatus3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStationStatus4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.pnlRun1.Location = new System.Drawing.Point(580, 51);
            this.pnlRun2.Location = new System.Drawing.Point(580, 121);
            this.pnlRun3.Location = new System.Drawing.Point(580, 191);
            this.pnlRun4.Location = new System.Drawing.Point(580, 261);
            this.pnlReady1.Location = new System.Drawing.Point(612, 51);
            this.pnlReady2.Location = new System.Drawing.Point(612, 121);
            this.pnlReady3.Location = new System.Drawing.Point(612, 191);
            this.pnlReady4.Location = new System.Drawing.Point(612, 261);
            this.pnlDone1.Location = new System.Drawing.Point(644, 51);
            this.pnlDone2.Location = new System.Drawing.Point(644, 121);
            this.pnlDone3.Location = new System.Drawing.Point(644, 191);
            this.pnlDone4.Location = new System.Drawing.Point(644, 261);
            this.pnlRun1.Size = new System.Drawing.Size(22, 22);
            this.pnlRun2.Size = new System.Drawing.Size(22, 22);
            this.pnlRun3.Size = new System.Drawing.Size(22, 22);
            this.pnlRun4.Size = new System.Drawing.Size(22, 22);
            this.pnlReady1.Size = new System.Drawing.Size(22, 22);
            this.pnlReady2.Size = new System.Drawing.Size(22, 22);
            this.pnlReady3.Size = new System.Drawing.Size(22, 22);
            this.pnlReady4.Size = new System.Drawing.Size(22, 22);
            this.pnlDone1.Size = new System.Drawing.Size(22, 22);
            this.pnlDone2.Size = new System.Drawing.Size(22, 22);
            this.pnlDone3.Size = new System.Drawing.Size(22, 22);
            this.pnlDone4.Size = new System.Drawing.Size(22, 22);
            this.btnS1Continuous.Location = new System.Drawing.Point(684, 46);
            this.btnS2Continuous.Location = new System.Drawing.Point(684, 116);
            this.btnS3Continuous.Location = new System.Drawing.Point(684, 186);
            this.btnS4Continuous.Location = new System.Drawing.Point(684, 256);
            this.btnS1Start.Location = new System.Drawing.Point(776, 46);
            this.btnS2Start.Location = new System.Drawing.Point(776, 116);
            this.btnS3Start.Location = new System.Drawing.Point(776, 186);
            this.btnS4Start.Location = new System.Drawing.Point(776, 256);
            this.btnS1Continuous.Size = new System.Drawing.Size(84, 34);
            this.btnS2Continuous.Size = new System.Drawing.Size(84, 34);
            this.btnS3Continuous.Size = new System.Drawing.Size(84, 34);
            this.btnS4Continuous.Size = new System.Drawing.Size(84, 34);
            this.btnS1Start.Size = new System.Drawing.Size(84, 34);
            this.btnS2Start.Size = new System.Drawing.Size(84, 34);
            this.btnS3Start.Size = new System.Drawing.Size(84, 34);
            this.btnS4Start.Size = new System.Drawing.Size(84, 34);
            this.btnS1Continuous.Text = "S1 连续";
            this.btnS2Continuous.Text = "S2 连续";
            this.btnS3Continuous.Text = "S3 连续";
            this.btnS4Continuous.Text = "S4 连续";
            this.btnS1Start.Text = "S1 启动";
            this.btnS2Start.Text = "S2 启动";
            this.btnS3Start.Text = "S3 启动";
            this.btnS4Start.Text = "S4 启动";
            this.pnlProcess.Controls.Add(this.lblStep1);
            this.pnlProcess.Controls.Add(this.lblStep2);
            this.pnlProcess.Controls.Add(this.lblStep3);
            this.pnlProcess.Controls.Add(this.lblStep4);
            this.pnlProcess.Controls.Add(this.lblStationStatus1);
            this.pnlProcess.Controls.Add(this.lblStationStatus2);
            this.pnlProcess.Controls.Add(this.lblStationStatus3);
            this.pnlProcess.Controls.Add(this.lblStationStatus4);
            this.pnlProcess.Controls.Add(this.pnlRun1);
            this.pnlProcess.Controls.Add(this.pnlRun2);
            this.pnlProcess.Controls.Add(this.pnlRun3);
            this.pnlProcess.Controls.Add(this.pnlRun4);
            this.pnlProcess.Controls.Add(this.pnlReady1);
            this.pnlProcess.Controls.Add(this.pnlReady2);
            this.pnlProcess.Controls.Add(this.pnlReady3);
            this.pnlProcess.Controls.Add(this.pnlReady4);
            this.pnlProcess.Controls.Add(this.pnlDone1);
            this.pnlProcess.Controls.Add(this.pnlDone2);
            this.pnlProcess.Controls.Add(this.pnlDone3);
            this.pnlProcess.Controls.Add(this.pnlDone4);
            this.pnlProcess.Controls.Add(this.btnS1Continuous);
            this.pnlProcess.Controls.Add(this.btnS2Continuous);
            this.pnlProcess.Controls.Add(this.btnS3Continuous);
            this.pnlProcess.Controls.Add(this.btnS4Continuous);
            this.pnlProcess.Controls.Add(this.btnS1Start);
            this.pnlProcess.Controls.Add(this.btnS2Start);
            this.pnlProcess.Controls.Add(this.btnS3Start);
            this.pnlProcess.Controls.Add(this.btnS4Start);

            this.pnlBottom.BackColor = System.Drawing.Color.White;
            this.pnlBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlBottom.Height = 76;
            this.btnManualMode.Location = new System.Drawing.Point(20, 12);
            this.btnAutoMode.Location = new System.Drawing.Point(196, 12);
            this.btnLineStart.Location = new System.Drawing.Point(372, 12);
            this.btnLinePause.Location = new System.Drawing.Point(548, 12);
            this.btnLineStop.Location = new System.Drawing.Point(724, 12);
            this.btnLineHome.Location = new System.Drawing.Point(900, 12);
            this.btnFaultReset.Location = new System.Drawing.Point(1076, 12);
            this.btnManualMode.Size = new System.Drawing.Size(164, 52);
            this.btnAutoMode.Size = new System.Drawing.Size(164, 52);
            this.btnLineStart.Size = new System.Drawing.Size(164, 52);
            this.btnLinePause.Size = new System.Drawing.Size(164, 52);
            this.btnLineStop.Size = new System.Drawing.Size(164, 52);
            this.btnLineHome.Size = new System.Drawing.Size(164, 52);
            this.btnFaultReset.Size = new System.Drawing.Size(164, 52);
            this.btnManualMode.Text = "手动";
            this.btnAutoMode.Text = "自动";
            this.btnLineStart.Text = "启动";
            this.btnLinePause.Text = "暂停";
            this.btnLineStop.Text = "停止";
            this.btnLineHome.Text = "回原位";
            this.btnFaultReset.Text = "故障复位";
            this.btnLineStart.BackColor = System.Drawing.Color.FromArgb(35, 156, 96);
            this.btnLineStart.ForeColor = System.Drawing.Color.White;
            this.btnLineStop.BackColor = System.Drawing.Color.FromArgb(201, 55, 58);
            this.btnLineStop.ForeColor = System.Drawing.Color.White;
            this.pnlBottom.Controls.Add(this.btnManualMode);
            this.pnlBottom.Controls.Add(this.btnAutoMode);
            this.pnlBottom.Controls.Add(this.btnLineStart);
            this.pnlBottom.Controls.Add(this.btnLinePause);
            this.pnlBottom.Controls.Add(this.btnLineStop);
            this.pnlBottom.Controls.Add(this.btnLineHome);
            this.pnlBottom.Controls.Add(this.btnFaultReset);

            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(232, 237, 243);
            this.ClientSize = new System.Drawing.Size(1440, 900);
            this.Controls.Add(this.pnlStationHeader);
            this.Controls.Add(this.pnlFlow);
            this.Controls.Add(this.pnlOverview);
            this.Controls.Add(this.pnlBottom);
            this.Controls.Add(this.pnlNavigation);
            this.Controls.Add(this.pnlHeader);
            this.Font = new System.Drawing.Font("Microsoft YaHei UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1280, 760);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "硅钢附着力测试仪";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            ((System.ComponentModel.ISupportInitialize)(this.dgvTasks)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
